trainer:
  simulator:
    smoothing_window_size: 1
    days_to_death: 21
    days_contagious: 8
    
  objective:
    scale: 10000
    
  bounds:
    r0_before:
      min: 0.1
      max: 5.0
    day_sd_start:
      min: 30
      max: 100
    r0_after:
      min: 0.01
      max: 0.99
    day_first_goner:
      min: 9
      max: 100
    sigmoid_param:
      min: 0.1
      max: 5.0

  niter: 100
  minimizer_kwargs:
    method: 'L-BFGS-B'
    options:
      'maxls': 1000
